version: '3.8'
services:
    mongo:
        image: mongo:latest
        container_name: mongo2
        #environment:
        #    MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
        #    MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        #    MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}
        env_file:
            - ./config/.env.dev
        volumes:
            - mongo:/data/db
        ports:
            - '6000:27017'
volumes:
    mongo: